version: "3.7"

services:
  database:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=everton
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    restart: always
    links:
      - database
    depends_on:
      - database
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app

volumes:
  pgdata:
